Repository luweglarz/ft_transcendence, pull requests merged in 2022-08, with the labels that each got.

#64 Game database
  docker-compose.yml
  src/backend/env/postgres.dev.env
  src/backend/prisma/migrations/20220728122759_game_migration/migration.sql
  src/backend/prisma/migrations/20220728154906_/migration.sql
  src/backend/prisma/schema.prisma
  src/backend/prisma/seed.ts
  src/backend/src/pong/class/ball/ball.ts
  src/backend/src/pong/controller/game/game.controller.spec.ts
  src/backend/src/pong/controller/game/game.controller.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.spec.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.spec.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.spec.ts
  src/backend/src/pong/pong.module.ts
  src/backend/src/pong/service/game-core/game-core.service.spec.ts
  src/backend/src/pong/service/game-core/game-core.service.ts
  src/backend/src/pong/service/game-db/game-db.service.spec.ts
  src/backend/src/pong/service/game-db/game-db.service.ts
  src/postgres/docker/Dockerfile
  src/postgres/docker/tools/postgres_setup.sh
Labels: enhancement

#69 Feat/front form validation
  src/backend/src/auth/auth.controller.ts
  src/backend/src/auth/auth.service.ts
  src/backend/src/auth/decorator/index.ts
  src/backend/src/auth/decorator/match-property.decorator.ts
  src/backend/src/auth/dto/auth.dto.ts
  src/backend/src/auth/dto/index.ts
  src/backend/src/auth/dto/local-auth.dto.ts
  src/backend/src/auth/dto/oauth.dto.ts
  src/frontend/src/app/app-routing.module.ts
  src/frontend/src/app/auth/auth.module.ts
  src/frontend/src/app/auth/info/index.ts
  src/frontend/src/app/auth/jwt/index.ts
  src/frontend/src/app/auth/jwt/jwt.module.ts
  src/frontend/src/app/auth/oauth/index.ts
  src/frontend/src/app/auth/oauth/oauth-callback.component.spec.ts
  src/frontend/src/app/auth/oauth/oauth-callback.component.ts
  src/frontend/src/app/auth/oauth/oauth.component.ts
  src/frontend/src/app/auth/oauth/oauth.service.ts
  src/frontend/src/app/auth/signin/signin.component.css
  src/frontend/src/app/auth/signin/signin.component.html
  src/frontend/src/app/auth/signin/signin.component.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signup/select/select.component.css
  src/frontend/src/app/auth/signup/select/select.component.html
  src/frontend/src/app/auth/signup/select/select.component.spec.ts
  src/frontend/src/app/auth/signup/select/select.component.ts
  src/frontend/src/app/auth/signup/signup.component.css
  src/frontend/src/app/auth/signup/signup.component.html
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/auth/signup/signup.module.ts
  src/frontend/src/app/auth/signup/signup.service.ts
  src/frontend/src/app/auth/signup/validators/validator-builder.service.spec.ts
  src/frontend/src/app/auth/signup/validators/validator-builder.service.ts
Labels: enhancement

#74 signout from navbar
  src/frontend/src/app/auth/signout/signout.component.ts
  src/frontend/src/app/home-page/home-page.module.ts
  src/frontend/src/app/home-page/navbar/navbar.component.css
  src/frontend/src/app/home-page/navbar/navbar.component.html
Labels: enhancement

#72 Websocket improvements
  Makefile
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/main.ts
  src/backend/src/pong/adapter/wildcardSocketioAdapter.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.spec.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.ts
  src/backend/src/pong/pong.module.ts
  src/backend/src/pong/service/game-core/game-core.service.spec.ts
  src/backend/src/pong/service/game-core/game-core.service.ts
  src/frontend/package-lock.json
  src/frontend/src/app/pong/class/game-socket.spec.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/game/game.service.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
  src/frontend/src/app/pong/pong.module.ts
  src/frontend/src/environments/environment.prod.ts
  src/frontend/src/environments/environment.ts
Labels: enhancement

#76 Update frontend packages
  src/frontend/angular.json
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/app/auth/signin/signin.component.ts
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/components/chat-room/chat-room.component.ts
  src/frontend/tsconfig.json
Labels: dependencies

#77 Avatar: refactor and fixes
  src/backend/prisma/schema.prisma
  src/backend/src/app.module.ts
  src/backend/src/auth/auth.controller.ts
  src/backend/src/auth/auth.service.ts
  src/backend/src/users/me/me.controller.spec.ts
  src/backend/src/users/me/me.controller.ts
  src/backend/src/users/public/users.controller.spec.ts
  src/backend/src/users/public/users.controller.ts
  src/backend/src/users/services/avatar/avatar.service.spec.ts
  src/backend/src/users/services/avatar/avatar.service.ts
  src/backend/src/users/users.module.ts
  src/frontend/src/app/auth/jwt/jwt.service.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signout/signout.service.ts
  src/frontend/src/app/avatar/avatar.service.ts
Labels: enhancement

#78 Chat: front module
  src/frontend/src/app/app.module.ts
  src/frontend/src/app/chat/chat.module.ts
  src/frontend/src/app/chat/chatService/chat.service.spec.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/class/auth-socket.spec.ts
  src/frontend/src/app/chat/class/auth-socket.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.css
  src/frontend/src/app/chat/components/chat-main/chat-main.component.html
  src/frontend/src/app/chat/components/chat-main/chat-main.component.spec.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-message/chat-message.component.css
  src/frontend/src/app/chat/components/chat-message/chat-message.component.html
  src/frontend/src/app/chat/components/chat-message/chat-message.component.spec.ts
  src/frontend/src/app/chat/components/chat-message/chat-message.component.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.css
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.html
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.spec.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.css
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.spec.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/app/chat/interface/message.ts
  src/frontend/src/app/chat/interface/room.ts
  src/frontend/src/app/chat/interface/roomUser.ts
  src/frontend/src/app/home-page/chatbar/chatbar.component.css
  src/frontend/src/app/home-page/chatbar/chatbar.component.html
  src/frontend/src/app/home-page/chatbar/chatbar.component.ts
  src/frontend/src/app/home-page/home-page.module.ts
Labels: enhancement

#81 Avatar: get any user's avatar
  src/backend/prisma/schema.prisma
  src/backend/src/users/public/users.controller.spec.ts
  src/backend/src/users/public/users.controller.ts
  src/backend/src/users/services/avatar/avatar.service.ts
  src/backend/src/users/services/users/users.service.spec.ts
  src/backend/src/users/services/users/users.service.ts
  src/backend/src/users/users.module.ts
  src/frontend/src/app/auth/info/info.component.html
  src/frontend/src/app/auth/info/info.component.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signout/signout.service.ts
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.component.ts
  src/frontend/src/app/avatar/avatar.module.ts
  src/frontend/src/app/avatar/avatar.service.ts
  src/frontend/src/app/avatar/directives/avatar.directive.spec.ts
  src/frontend/src/app/avatar/directives/avatar.directive.ts
  src/frontend/src/app/home-page/home-page.module.ts
  src/frontend/src/app/home-page/navbar/navbar.component.html
  src/frontend/src/app/home-page/navbar/navbar.component.ts
  src/frontend/src/app/home-page/popups/profil/profil.component.html
  src/frontend/src/app/home-page/popups/profil/profil.component.ts
Labels: enhancement

#82 Auth: backend refact
  src/backend/prisma/schema.prisma
  src/backend/prisma/seed.ts
  src/backend/src/auth/auth.controller.spec.ts
  src/backend/src/auth/auth.controller.ts
  src/backend/src/auth/auth.module.ts
  src/backend/src/auth/auth.service.ts
  src/backend/src/auth/decorators/index.ts
  src/backend/src/auth/decorators/user.decorator.ts
  src/backend/src/auth/index.ts
  src/backend/src/auth/modules/jwt/guard/index.ts
  src/backend/src/auth/modules/jwt/guard/jwt.guard.ts
  src/backend/src/auth/modules/jwt/index.ts
  src/backend/src/auth/modules/jwt/interfaces/index.ts
  src/backend/src/auth/modules/jwt/interfaces/jwt-payload.interface.ts
  src/backend/src/auth/modules/jwt/jwt-auth.controller.spec.ts
  src/backend/src/auth/modules/jwt/jwt-auth.controller.ts
  src/backend/src/auth/modules/jwt/jwt-auth.module.ts
  src/backend/src/auth/modules/jwt/jwt-auth.service.spec.ts
  src/backend/src/auth/modules/jwt/jwt-auth.service.ts
  src/backend/src/auth/modules/jwt/strategy/index.ts
  src/backend/src/auth/modules/jwt/strategy/jwt.strategy.ts
  src/backend/src/auth/modules/local/dto/index.ts
  src/backend/src/auth/modules/local/dto/local-auth.dto.ts
  src/backend/src/auth/modules/local/local-auth.controller.spec.ts
  src/backend/src/auth/modules/local/local-auth.controller.ts
  src/backend/src/auth/modules/local/local-auth.module.ts
  src/backend/src/auth/modules/local/local-auth.service.spec.ts
  src/backend/src/auth/modules/local/local-auth.service.ts
  src/backend/src/auth/modules/oauth/dto/index.ts
  src/backend/src/auth/modules/oauth/dto/oauth.dto.ts
  src/backend/src/auth/modules/oauth/guard/index.ts
  src/backend/src/auth/modules/oauth/guard/oauth2.guard.ts
  src/backend/src/auth/modules/oauth/oauth.controller.spec.ts
  src/backend/src/auth/modules/oauth/oauth.controller.ts
  src/backend/src/auth/modules/oauth/oauth.module.ts
  src/backend/src/auth/modules/oauth/oauth.service.spec.ts
  src/backend/src/auth/modules/oauth/oauth.service.ts
  src/backend/src/auth/modules/oauth/strategy/index.ts
  src/backend/src/auth/modules/oauth/strategy/oauth2.strategy.ts
  src/backend/src/auth/modules/utils/auth-utils.controller.spec.ts
  src/backend/src/auth/modules/utils/auth-utils.controller.ts
  src/backend/src/auth/modules/utils/auth-utils.module.ts
  src/backend/src/auth/modules/utils/auth-utils.service.spec.ts
  src/backend/src/auth/modules/utils/auth-utils.service.ts
  src/backend/src/auth/routes.ts
  src/backend/src/chat/chat.gateway.spec.ts
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/chat.module.ts
  src/backend/src/db/db.service.spec.ts
  src/backend/src/pong/gateway/game/game-gateway.service.spec.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.spec.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.spec.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.spec.ts
  src/backend/src/pong/pong.module.ts
  src/backend/src/pong/service/game-core/game-core.service.spec.ts
  src/backend/src/users/me/me.controller.ts
  src/backend/src/users/services/avatar/avatar.service.ts
  src/frontend/src/app/auth/auth.module.ts
Labels: enhancement

#84 Chat
  src/backend/prisma/schema.prisma
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/room/room.service.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/class/auth-socket.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.spec.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.html
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/environments/environment.prod.ts
  src/frontend/src/environments/environment.ts
Labels: enhancement

#80 Custom game mode
  src/backend/package-lock.json
  src/backend/src/pong/class/ball/ball.spec.ts
  src/backend/src/pong/class/ball/ball.ts
  src/backend/src/pong/class/game-map/game-map.spec.ts
  src/backend/src/pong/class/game-map/game-map.ts
  src/backend/src/pong/class/game-mode/custom-game/custom-game.spec.ts
  src/backend/src/pong/class/game-mode/custom-game/custom-game.ts
  src/backend/src/pong/class/game-mode/normal-game/normal-game.spec.ts
  src/backend/src/pong/class/game-mode/normal-game/normal-game.ts
  src/backend/src/pong/class/player/player.ts
  src/backend/src/pong/class/room/room.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.ts
  src/backend/src/pong/interface/game-mode.interface.ts
  src/backend/src/pong/service/game-core/game-core.service.ts
  src/frontend/package-lock.json
  src/frontend/src/app/pong/class/ball.ts
  src/frontend/src/app/pong/class/game-mode/custom-game.spec.ts
  src/frontend/src/app/pong/class/game-mode/custom-game.ts
  src/frontend/src/app/pong/class/game-mode/normal-game.spec.ts
  src/frontend/src/app/pong/class/game-mode/normal-game.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/class/game.spec.ts
  src/frontend/src/app/pong/class/game.ts
  src/frontend/src/app/pong/class/player.ts
  src/frontend/src/app/pong/class/stop-watch.spec.ts
  src/frontend/src/app/pong/class/stop-watch.ts
  src/frontend/src/app/pong/game/game.component.css
  src/frontend/src/app/pong/game/game.component.html
  src/frontend/src/app/pong/game/game.component.ts
  src/frontend/src/app/pong/game/game.service.ts
  src/frontend/src/app/pong/game/is-in-game.guard.spec.ts
  src/frontend/src/app/pong/game/is-in-game.guard.ts
  src/frontend/src/app/pong/interface/game-mode.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.html
  src/frontend/src/app/pong/matchmaking/matchmaking.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: enhancement

#87 Improve game frontend
  src/backend/src/pong/class/game-mode/custom-game/custom-game.ts
  src/backend/src/pong/class/game-mode/normal-game/normal-game.ts
  src/frontend/src/app/pong/class/game-mode/custom-game.ts
  src/frontend/src/app/pong/class/game-mode/normal-game.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/game/game.component.css
  src/frontend/src/app/pong/game/game.component.html
  src/frontend/src/app/pong/game/game.component.ts
  src/frontend/src/app/pong/game/game.service.ts
  src/frontend/src/app/pong/interface/game-mode.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.html
  src/frontend/src/app/pong/pong.module.ts
  src/frontend/src/assets/pong/ball.png
  src/frontend/src/assets/pong/football-pitch.jpeg
  src/frontend/src/assets/pong/paddleOneSkin.jpeg
  src/frontend/src/assets/pong/paddleTwoSkin.jpeg
Labels: enhancement

#95 Fixing the scrolling for matchHistoryComponent in profil
  src/frontend/src/app/home-page/popups/profil/match-history/match-history.component.css
  src/frontend/src/app/home-page/popups/profil/match-history/match-history.component.html
  src/frontend/src/app/home-page/popups/profil/match-history/match-history.component.ts
  src/frontend/src/app/home-page/popups/profil/profil.component.css
  src/frontend/src/app/home-page/popups/profil/profil.component.html
Labels: bug

#99 Implement refresh tokens
  src/backend/src/auth/decorators/user.decorator.ts
  src/backend/src/auth/modules/jwt/dto/index.ts
  src/backend/src/auth/modules/jwt/dto/jwt.dto.ts
  src/backend/src/auth/modules/jwt/dto/tokens.dto.ts
  src/backend/src/auth/modules/jwt/guard/jwt.guard.ts
  src/backend/src/auth/modules/jwt/interfaces/index.ts
  src/backend/src/auth/modules/jwt/interfaces/jwt-payload.interface.ts
  src/backend/src/auth/modules/jwt/jwt-auth.controller.spec.ts
  src/backend/src/auth/modules/jwt/jwt-auth.controller.ts
  src/backend/src/auth/modules/jwt/jwt-auth.module.ts
  src/backend/src/auth/modules/jwt/jwt-auth.service.spec.ts
  src/backend/src/auth/modules/jwt/jwt-auth.service.ts
  src/backend/src/auth/modules/jwt/strategy/jwt.strategy.ts
  src/backend/src/auth/modules/oauth/dto/oauth.dto.ts
  src/backend/src/auth/modules/oauth/oauth.controller.ts
  src/backend/src/auth/modules/oauth/oauth.module.ts
  src/backend/src/auth/modules/oauth/oauth.service.ts
  src/backend/src/auth/modules/utils/auth-utils.controller.ts
  src/backend/src/auth/modules/utils/auth-utils.service.ts
  src/backend/src/auth/modules/utils/dto/signin-success.dto.ts
  src/backend/src/pong/gateway/game/game-gateway.service.spec.ts
  src/backend/src/users/me/me.controller.ts
  src/backend/src/users/services/avatar/avatar.service.ts
  src/frontend/src/app/auth/auth.config.ts
  src/frontend/src/app/auth/info/info.component.html
  src/frontend/src/app/auth/info/info.component.ts
  src/frontend/src/app/auth/interface/auth.interface.ts
  src/frontend/src/app/auth/interface/index.ts
  src/frontend/src/app/auth/jwt/dto/index.ts
  src/frontend/src/app/auth/jwt/dto/jwt.dto.ts
  src/frontend/src/app/auth/jwt/dto/tokens.dto.ts
  src/frontend/src/app/auth/jwt/index.ts
  src/frontend/src/app/auth/jwt/jwt.interceptor.ts
  src/frontend/src/app/auth/jwt/jwt.service.ts
  src/frontend/src/app/auth/oauth/dto/auth.dto.ts
  src/frontend/src/app/auth/oauth/dto/index.ts
  src/frontend/src/app/auth/oauth/oauth.service.ts
  src/frontend/src/app/auth/signin/dto/signin-success.dto.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signout/signout.service.ts
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/auth/signup/signup.service.ts
  src/frontend/src/app/avatar/avatar.service.ts
  src/frontend/src/app/chat/class/auth-socket.ts
  src/frontend/src/app/home-page/navbar/navbar.component.ts
  src/frontend/src/app/pong/class/game-socket.ts
Labels: enhancement

#103 Chat
  src/backend/prisma/schema.prisma
  src/backend/src/chat/chat.gateway.spec.ts
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/chat.module.ts
  src/backend/src/chat/command/command.service.ts
  src/backend/src/chat/jail-user/jailUser.service.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
Labels: enhancement

#114 Fix postgres healthcheck command
  docker-compose.yml
Labels: bug

#113 Chat
  src/backend/prisma/schema.prisma
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/command/command.service.ts
  src/frontend/src/app/chat/chat.module.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.css
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.html
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.html
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/interface/invite.ts
Labels: enhancement
