Repository luweglarz/ft_transcendence, pull requests merged in 2022-09, with the labels that each got.

#115 Auth & Avatar: various enhancements
  src/backend/.vscode/settings.json
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/prisma/schema.prisma
  src/backend/prisma/seed.ts
  src/backend/src/auth/modules/authenticator/authenticator.service.ts
  src/backend/src/auth/modules/local/dto/local-auth.dto.ts
  src/backend/src/auth/modules/local/local-auth.service.ts
  src/backend/src/auth/modules/oauth/dto/oauth.dto.ts
  src/backend/src/auth/modules/oauth/oauth.service.ts
  src/backend/src/auth/modules/utils/auth-utils.controller.ts
  src/backend/src/auth/modules/utils/auth-utils.service.ts
  src/backend/src/db/db.service.spec.ts
  src/backend/src/users/me/me.controller.ts
  src/frontend/src/app/auth/jwt/jwt.service.ts
  src/frontend/src/app/auth/oauth/dto/auth.dto.ts
  src/frontend/src/app/auth/signin/signin.component.html
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signout/signout.service.ts
  src/frontend/src/app/auth/signup/signup.component.html
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.component.css
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.component.html
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.component.ts
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.service.spec.ts
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.service.ts
  src/frontend/src/app/avatar/avatar.service.ts
  src/frontend/src/app/avatar/directives/avatar.directive.ts
  src/frontend/src/app/services/events.service.spec.ts
  src/frontend/src/app/services/events.service.ts
  src/frontend/src/assets/assets.ts
Labels: enhancement

#119 added profil access through chat
  src/frontend/src/app/avatar/directives/avatar.directive.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.css
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
Labels: enhancement

#116 Improve the websocket authentification
  src/backend/package-lock.json
  src/backend/package.json
  src/backend/src/main.ts
  src/backend/src/pong/adapter/wildcardSocketioAdapter.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/game/game.component.css
  src/frontend/src/app/pong/game/game.component.html
  src/frontend/src/app/pong/game/game.component.ts
  src/frontend/src/app/pong/game/game.service.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: bug, enhancement

#120 Auth enhancements
  src/backend/src/auth/modules/oauth/dto/oauth.dto.ts
  src/backend/src/auth/modules/oauth/oauth.controller.ts
  src/backend/src/auth/modules/oauth/oauth.service.ts
  src/frontend/src/app/app-routing.module.ts
  src/frontend/src/app/auth/jwt/guard/is-signed-in.guard.spec.ts
  src/frontend/src/app/auth/jwt/guard/is-signed-in.guard.ts
  src/frontend/src/app/auth/jwt/jwt.service.ts
  src/frontend/src/app/auth/oauth/dto/auth.dto.ts
  src/frontend/src/app/auth/oauth/oauth.service.ts
  src/frontend/src/app/auth/signin/signin.component.html
  src/frontend/src/app/auth/signin/signin.component.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signup/select/select.component.html
  src/frontend/src/app/auth/signup/signup.component.css
  src/frontend/src/app/auth/signup/signup.component.html
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/auth/two-factors/otp-page/otp-page.component.ts
Labels: enhancement

#123 Spectating a game
  src/backend/prisma/schema.prisma
  src/backend/src/app.module.ts
  src/backend/src/direct-message/direct-messages.controller.spec.ts
  src/backend/src/direct-message/direct-messages.controller.ts
  src/backend/src/direct-message/direct-messages.module.ts
  src/backend/src/direct-message/direct-messages.service.spec.ts
  src/backend/src/direct-message/direct-messages.service.ts
  src/backend/src/pong/controller/game/game.controller.spec.ts
  src/backend/src/pong/controller/game/game.controller.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/pong.module.ts
  src/backend/src/social/gateway/friends-status-gateway.gateway.spec.ts
  src/backend/src/social/gateway/friends-status-gateway.gateway.ts
  src/backend/src/social/social.controller.spec.ts
  src/backend/src/social/social.controller.ts
  src/backend/src/social/social.module.ts
  src/backend/src/social/social.service.spec.ts
  src/backend/src/social/social.service.ts
  src/frontend/src/app/app.component.ts
  src/frontend/src/app/auth/signin/signin.component.css
  src/frontend/src/app/chat/chat.module.ts
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.html
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.css
  src/frontend/src/app/chat/components/chat-main/chat-main.component.html
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-message/chat-message.component.css
  src/frontend/src/app/chat/components/chat-message/chat-message.component.html
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.css
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.html
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.css
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/app/chat/interface/roomUser.ts
  src/frontend/src/app/home-page/navbar/navbar.component.html
  src/frontend/src/app/home-page/navbar/navbar.component.ts
  src/frontend/src/app/home-page/popups/ladder/ladder.component.css
  src/frontend/src/app/home-page/popups/ladder/ladder.component.html
  src/frontend/src/app/home-page/popups/ladder/ladder.component.ts
  src/frontend/src/app/home-page/popups/popups.module.ts
  src/frontend/src/app/home-page/popups/popups.service.ts
  src/frontend/src/app/home-page/popups/social/class/status-socket.spec.ts
  src/frontend/src/app/home-page/popups/social/class/status-socket.ts
  src/frontend/src/app/home-page/popups/social/direct-messages.service.spec.ts
  src/frontend/src/app/home-page/popups/social/direct-messages.service.ts
  src/frontend/src/app/home-page/popups/social/interfaces/social.ts
  src/frontend/src/app/home-page/popups/social/social.component.css
  src/frontend/src/app/home-page/popups/social/social.component.html
  src/frontend/src/app/home-page/popups/social/social.component.ts
  src/frontend/src/app/home-page/popups/social/social.service.spec.ts
  src/frontend/src/app/home-page/popups/social/social.service.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/game/game.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.css
  src/frontend/src/environments/environment.prod.ts
  src/frontend/src/environments/environment.ts
Labels: enhancement

#126 Chat
  src/backend/src/chat/chat.gateway.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.ts
Labels: enhancement

#122 Chat style
  src/backend/prisma/schema.prisma
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/command/command.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.css
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.html
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.css
  src/frontend/src/app/chat/components/chat-main/chat-main.component.html
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-message/chat-message.component.css
  src/frontend/src/app/chat/components/chat-message/chat-message.component.html
  src/frontend/src/app/chat/components/chat-message/chat-message.component.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.css
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.css
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/app/chat/interface/invite.ts
  src/frontend/src/app/chat/interface/message.ts
  src/frontend/src/app/home-page/popups/social/social.service.ts
  src/frontend/src/app/home-page/services/notification.service.ts
  src/frontend/src/assets/sounds/gamefound.wav
  src/frontend/src/assets/sounds/invitation.wav
Labels: enhancement

#127 popup history + fix chat open profile button
  src/frontend/src/app/app-routing.module.ts
  src/frontend/src/app/auth/oauth/oauth.service.ts
  src/frontend/src/app/auth/signin/signin.component.ts
  src/frontend/src/app/auth/signin/signin.service.ts
  src/frontend/src/app/auth/signup/signup.component.ts
  src/frontend/src/app/auth/two-factors/qrcode/qrcode.component.ts
  src/frontend/src/app/avatar/directives/avatar.directive.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/home-page/home.component.html
  src/frontend/src/app/home-page/popups/ladder/ladder.component.ts
  src/frontend/src/app/home-page/popups/popups.component.html
  src/frontend/src/app/home-page/popups/popups.component.ts
  src/frontend/src/app/home-page/popups/popups.service.ts
  src/frontend/src/app/pong/class/game-mode/custom-game.ts
  src/frontend/src/app/pong/class/game-mode/normal-game.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/game/game.component.ts
  src/frontend/src/app/pong/game/game.service.ts
  src/frontend/src/app/pong/guard/is-in-game.guard.spec.ts
  src/frontend/src/app/pong/guard/is-in-game.guard.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.html
  src/frontend/src/app/pong/matchmaking/matchmaking.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: enhancement

#125 Invitation to a private game
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/pong.module.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.html
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/app/home-page/home-page.module.ts
  src/frontend/src/app/home-page/home.component.html
  src/frontend/src/app/home-page/home.component.ts
  src/frontend/src/app/home-page/invite/invite.component.css
  src/frontend/src/app/home-page/invite/invite.component.html
  src/frontend/src/app/home-page/invite/invite.component.spec.ts
  src/frontend/src/app/home-page/invite/invite.component.ts
  src/frontend/src/app/home-page/popups/ladder/ladder.component.html
  src/frontend/src/app/home-page/popups/ladder/ladder.component.ts
  src/frontend/src/app/home-page/services/invite.service.spec.ts
  src/frontend/src/app/home-page/services/invite.service.ts
  src/frontend/src/app/home-page/services/wait.service.spec.ts
  src/frontend/src/app/home-page/services/wait.service.ts
  src/frontend/src/app/home-page/wait/wait.component.css
  src/frontend/src/app/home-page/wait/wait.component.html
  src/frontend/src/app/home-page/wait/wait.component.spec.ts
  src/frontend/src/app/home-page/wait/wait.component.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: enhancement

#130 Fix/game invite
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
  src/frontend/src/app/home-page/home-page.module.ts
  src/frontend/src/app/home-page/home.component.ts
  src/frontend/src/app/home-page/popups/ladder/ladder.component.ts
  src/frontend/src/app/home-page/popups/social/class/status-socket.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/matchmaking/invite/invite.component.css
  src/frontend/src/app/pong/matchmaking/invite/invite.component.html
  src/frontend/src/app/pong/matchmaking/invite/invite.component.spec.ts
  src/frontend/src/app/pong/matchmaking/invite/invite.component.ts
  src/frontend/src/app/pong/matchmaking/invite/invite.service.spec.ts
  src/frontend/src/app/pong/matchmaking/invite/invite.service.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.component.html
  src/frontend/src/app/pong/matchmaking/matchmaking.component.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
  src/frontend/src/app/pong/matchmaking/wait/wait.component.css
  src/frontend/src/app/pong/matchmaking/wait/wait.component.html
  src/frontend/src/app/pong/matchmaking/wait/wait.component.spec.ts
  src/frontend/src/app/pong/matchmaking/wait/wait.component.ts
  src/frontend/src/app/pong/matchmaking/wait/wait.service.spec.ts
  src/frontend/src/app/pong/matchmaking/wait/wait.service.ts
  src/frontend/src/app/pong/pong.module.ts
Labels: bug

#133 Fix/game invite
  src/frontend/src/app/pong/class/game-socket.ts
Labels: bug

#132 fix chat auth after a signout->signin.
  src/frontend/src/app/chat/chatService/chat.service.ts
Labels: bug

#135 Edit user settings (avatar and username)
  src/backend/src/auth/modules/jwt/jwt-auth.service.ts
  src/backend/src/auth/modules/two-factors/two-factors.controller.ts
  src/backend/src/auth/modules/two-factors/two-factors.service.ts
  src/backend/src/auth/modules/utils/auth-utils.service.ts
  src/backend/src/users/me/dto/usernameUpdate.dto.ts
  src/backend/src/users/me/me.controller.spec.ts
  src/backend/src/users/me/me.controller.ts
  src/backend/src/users/services/avatar/avatar.service.ts
  src/backend/src/users/services/users/users.service.ts
  src/frontend/src/app/auth/jwt/jwt.service.ts
  src/frontend/src/app/auth/signin/signin.component.css
  src/frontend/src/app/auth/signup/signup.component.css
  src/frontend/src/app/auth/two-factors/qrcode/qrcode.component.css
  src/frontend/src/app/auth/two-factors/qrcode/qrcode.component.html
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.component.html
  src/frontend/src/app/avatar/avatar-upload/avatar-upload.service.ts
  src/frontend/src/app/home-page/popups/popups.module.ts
  src/frontend/src/app/home-page/popups/settings/dto/username-update.dto.ts
  src/frontend/src/app/home-page/popups/settings/settings.component.css
  src/frontend/src/app/home-page/popups/settings/settings.component.html
  src/frontend/src/app/home-page/popups/settings/settings.component.ts
  src/frontend/src/app/home-page/popups/settings/settings.service.spec.ts
  src/frontend/src/app/home-page/popups/settings/settings.service.ts
  src/frontend/src/app/services/events.service.ts
Labels: enhancement

#138 User reconnection to a game
  src/backend/src/pong/class/player/player.ts
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: enhancement

#137 kick and leave command
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/command/command.service.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
Labels: enhancement

#139 Fix typos and add building section
  README.md
Labels: documentation

#141 Pong console cleanup
  src/backend/src/pong/gateway/game/game-gateway.service.ts
  src/backend/src/pong/gateway/game/game.gateway.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking-gateway.service.ts
  src/backend/src/pong/gateway/matchmaking/matchmaking.gateway.ts
  src/frontend/src/app/pong/class/game-socket.ts
  src/frontend/src/app/pong/matchmaking/matchmaking.service.ts
Labels: enhancement

#142 Chat
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/chat/command/command.service.ts
  src/backend/src/chat/jail-user/jailUser.service.ts
  src/backend/src/chat/room/room.service.ts
  src/frontend/src/app/chat/chatService/chat.service.ts
  src/frontend/src/app/chat/components/chat-invite/chat-invite.component.ts
  src/frontend/src/app/chat/components/chat-main/chat-main.component.ts
  src/frontend/src/app/chat/components/chat-message/chat-message.component.ts
  src/frontend/src/app/chat/components/chat-room-create/chat-room-create.component.ts
  src/frontend/src/app/chat/components/chat-room/chat-room.component.ts
Labels: enhancement

#144 Add the commands documentation
  README.md
Labels: documentation

#146 Catch async verifyAccessToken excetpion on friendsStatusGateway
  src/backend/src/social/gateway/friends-status-gateway.gateway.ts
Labels: bug

#149 Status hot fix when a user is connected on more than one navigator
  src/backend/src/chat/chat.gateway.ts
  src/backend/src/social/gateway/friends-status-gateway.gateway.ts
Labels: bug

#151 Add whisper command to the README
  README.md
Labels: documentation
